import {createStore} from "vuex"
import * as actions from "./actions";
import * as mutations from "./mutations";
const store = createStore({
    state:{
        user:{
            token:sessionStorage.getItem('TOKEN'),
            data: {},
        },
        articles:{
            loading:false,
            data:[],
            links:[],
            from: null,
            to: null,
            page: 1,
            limit: null,
            total: null,
        },
        banners:{
            loading:false,
            data:[],
            links:[],
            from: null,
            to: null,
            page: 1,
            limit: null,
            total: null,
        },
        chairmans:{
            loading:false,
            data:[],
            links:[],
            from: null,
            to: null,
            page: 1,
            limit: null,
            total: null,
        },
        organizations:{
            loading:false,
            data:[],
            links:[],
            from: null,
            to: null,
            page: 1,
            limit: null,
            total: null,
        },
        awardprograms:{
            loading:false,
            data:[],
            links:[],
            from: null,
            to: null,
            page: 1,
            limit: null,
            total: null,
        },
        letters:{
            loading:false,
            data:[],
            links:[],
            from: null,
            to: null,
            page: 1,
            limit: null,
            total: null,
        },
        cstdatabases:{
            loading:false,
            data:[],
            links:[],
            from: null,
            to: null,
            page: 1,
            limit: null,
            total: null,
        },
        cstseminars:{
            loading:false,
            data:[],
            links:[],
            from: null,
            to: null,
            page: 1,
            limit: null,
            total: null,
        },
        overseas:{
            loading:false,
            data:[],
            links:[],
            from: null,
            to: null,
            page: 1,
            limit: null,
            total: null,
        },
        forums:{
            loading:false,
            data:[],
            links:[],
            from: null,
            to: null,
            page: 1,
            limit: null,
            total: null,
        },
    },
    getters:{},
    actions,
    mutations,
});

export default store;